name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mettez à jour vers la version 3

      # Ajoutez d'autres étapes ici


      - name: Update CSS/JS version
        run: |
          # Ajouter un paramètre de version aléatoire à la fin des fichiers CSS/JS dans index.html
          sed -i 's/\(main.js?v=\)[0-9]\+/\1'$RANDOM'/' index.html
          sed -i 's/\(style.css?v=\)[0-9]\+/\1'$RANDOM'/' index.html

      - name: Push changes back to GitHub
        run: |
          git config --global user.email "rjeantsioriniaina@gmail.com"
          git config --global user.name "rjeantsioriniaina"
          git add index.html
          git commit -m "Cache busting for CSS/JS"
          git push
